# Generated by Django 5.0.2 on 2024-02-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_category_user_alter_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
